---
version: "3.4"
services:
  netbox:
    build:
      dockerfile: Dockerfile-plugin_dev
      context: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ../:/opt/netbox-facts
      - ~/.gitconfig:/home/ubuntu/.gitconfig:z,ro
      - ~/.ssh:/home/ubuntu/.ssh
      - ./home/.config/:/home/ubuntu/.config/
