ARG NETBOX_VARIANT=v3.7

FROM netboxcommunity/netbox:${NETBOX_VARIANT}

ARG NETBOX_INITIALIZERS_VARIANT=3.7.*

ARG DEBIAN_FRONTEND=noninteractive

# Install APT packages
# hadolint ignore=DL3008
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends curl git make openssh-client python3.11-dev sudo wget fish \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install development & ide dependencies
COPY requirements_dev.txt /tmp/pip-tmp/
RUN /opt/netbox/venv/bin/python3 -m pip install --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements_dev.txt \
    && rm -rf /tmp/*

ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN chsh -s /usr/bin/fish $USERNAME; \
    chown -R $USER_UID:$USER_GID /home/ubuntu; \
    usermod -aG sudo $USERNAME \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY . /opt/netbox-facts

RUN chown $USERNAME:$USERNAME /opt/netbox-facts /opt/netbox /etc/netbox /opt/unit -R

USER ${USERNAME}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Add ohmyfish
RUN curl -L https://get.oh-my.fish > /tmp/install_omf && fish /tmp/install_omf --noninteractive && rm /tmp/install_omf
RUN fish -c "omf install bobthefish"

RUN /opt/netbox/venv/bin/pip install --no-warn-script-location netbox-initializers==$NETBOX_INITIALIZERS_VARIANT

WORKDIR ${PLUGIN_PATH}
RUN /opt/netbox/venv/bin/pip install --editable /opt/netbox-facts

# hadolint ignore=DL3002
USER root

COPY .devcontainer/entrypoint-dev.sh /bin/entrypoint-dev.sh
RUN chmod +x /bin/entrypoint-dev.sh

ENTRYPOINT ["/bin/entrypoint-dev.sh"]
