"""Facts Report models."""

from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from netbox.models import NetBoxModel

from ..choices import (
    CollectionTypeChoices,
    EntryActionChoices,
    EntryStatusChoices,
    ReportStatusChoices,
)


class FactsReport(NetBoxModel):
    """A report generated by a collection plan run."""

    collection_plan = models.ForeignKey(
        to="netbox_facts.CollectionPlan",
        on_delete=models.CASCADE,
        related_name="reports",
    )
    job = models.ForeignKey(
        to="core.Job",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    status = models.CharField(
        max_length=50,
        choices=ReportStatusChoices,
        default=ReportStatusChoices.STATUS_PENDING,
    )
    created_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    completed_at = models.DateTimeField(null=True, blank=True)
    summary = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Cached entry counts by action: {new, changed, confirmed, stale}"),
    )
    comments = models.TextField(blank=True)

    class Meta:
        ordering = ["-created"]
        verbose_name = _("Facts Report")
        verbose_name_plural = _("Facts Reports")
        permissions = [
            ("apply_factsreport", "Can apply facts report entries"),
        ]

    def __str__(self):
        return f"Report #{self.pk} — {self.collection_plan}"

    def get_absolute_url(self):
        return reverse("plugins:netbox_facts:factsreport", args=[self.pk])

    def get_status_color(self):
        return ReportStatusChoices.colors.get(self.status)

    def update_summary(self):
        """Recompute cached summary counts from entries."""
        from django.db.models import Count

        counts = (
            self.entries.values("action")
            .annotate(count=Count("id"))
            .order_by()
        )
        self.summary = {
            EntryActionChoices.ACTION_NEW: 0,
            EntryActionChoices.ACTION_CHANGED: 0,
            EntryActionChoices.ACTION_CONFIRMED: 0,
            EntryActionChoices.ACTION_STALE: 0,
        }
        for row in counts:
            self.summary[row["action"]] = row["count"]
        self.save(update_fields=["summary"])


class FactsReportEntry(models.Model):
    """A single detected fact within a FactsReport."""

    report = models.ForeignKey(
        FactsReport,
        on_delete=models.CASCADE,
        related_name="entries",
    )
    action = models.CharField(max_length=50, choices=EntryActionChoices)
    status = models.CharField(
        max_length=50,
        choices=EntryStatusChoices,
        default=EntryStatusChoices.STATUS_PENDING,
    )
    collector_type = models.CharField(max_length=50, choices=CollectionTypeChoices)
    device = models.ForeignKey(
        to="dcim.Device",
        on_delete=models.CASCADE,
        related_name="+",
    )

    # Generic FK to the target NetBox object (nullable for new entries pre-apply)
    object_type = models.ForeignKey(
        ContentType,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    object_id = models.PositiveBigIntegerField(null=True, blank=True)
    object = GenericForeignKey("object_type", "object_id")

    object_repr = models.CharField(
        max_length=300,
        blank=True,
        help_text=_("Human-readable label, e.g. 'Interface ge-0/0/0'"),
    )
    detected_values = models.JSONField(
        default=dict,
        help_text=_("What the device reported"),
    )
    current_values = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("What NetBox currently has (empty for new)"),
    )
    error_message = models.TextField(
        blank=True,
        help_text=_("Populated on apply failure"),
    )

    created = models.DateTimeField(auto_now_add=True)
    applied_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["created"]
        verbose_name = _("Facts Report Entry")
        verbose_name_plural = _("Facts Report Entries")
        indexes = [
            models.Index(fields=["report", "action"]),
            models.Index(fields=["report", "status"]),
            models.Index(fields=["object_type", "object_id"]),
        ]

    def __str__(self):
        return f"{self.get_action_display()} — {self.object_repr}"

    def get_action_color(self):
        return EntryActionChoices.colors.get(self.action)

    def get_status_color(self):
        return EntryStatusChoices.colors.get(self.status)
