# Generated by Django 4.1.10 on 2023-08-03 20:30

import dcim.fields
from django.db import migrations, models
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extras", "0092_delete_jobresult"),
        ("dcim", "0172_larger_power_draw_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="MACAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("mac_address", dcim.fields.MACAddressField(unique=True)),
                (
                    "seen_by_interfaces",
                    models.ManyToManyField(related_name="known_mac_addresses", to="dcim.interface"),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("mac_address",),
            },
        ),
    ]
