# Generated by Django 4.1.10 on 2023-08-07 17:52

import dcim.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0092_delete_jobresult'),
        ('dcim', '0172_larger_power_draw_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='MACVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('mac_prefix', models.CharField(max_length=8, unique=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MACAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('mac_address', dcim.fields.MACAddressField(unique=True)),
                ('comments', models.TextField(blank=True)),
                ('seen_by_interfaces', models.ManyToManyField(related_name='known_mac_addresses', to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='netbox_facts.macvendor')),
            ],
            options={
                'verbose_name': 'MAC Address',
                'verbose_name_plural': 'MAC Addresses',
                'ordering': ('mac_address',),
            },
        ),
        migrations.AddIndex(
            model_name='macaddress',
            index=models.Index(fields=['mac_address'], name='netbox_fact_mac_add_e18267_idx'),
        ),
    ]
