# Generated by Django 4.1.10 on 2023-08-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macvendor',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
