# Generated by Django 4.2.6 on 2023-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macvendor',
            options={'ordering': ('manufacturer', 'vendor_name')},
        ),
        migrations.AddField(
            model_name='macvendor',
            name='vendor_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
