# Generated by Django 4.1.10 on 2023-08-07 19:39

from django.db import migrations
import netbox_facts.fields


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0003_alter_macvendor_options_alter_macvendor_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macvendor',
            name='mac_prefix',
            field=netbox_facts.fields.MACPrefixField(max_length=8, unique=True),
        ),
    ]
