# Generated by Django 4.2.6 on 2023-11-02 14:58

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_facts", "0004_remove_collectordefinition_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectordefinition",
            name="interval",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collectordefinition",
            name="schedule_at",
            field=models.DateTimeField(default=datetime.utcnow()),
            preserve_default=False,
        ),
    ]
