# Generated by Django 4.1.10 on 2023-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0004_alter_macvendor_mac_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaddress',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='macvendor',
            index=models.Index(fields=['mac_prefix'], name='netbox_fact_mac_pre_4b5d5e_idx'),
        ),
    ]
