# Generated by Django 4.2.6 on 2023-11-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0005_collectordefinition_interval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectordefinition',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.RemoveField(
            model_name='collectordefinition',
            name='weight',
        ),
        migrations.AddField(
            model_name='collectordefinition',
            name='priority',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='collectordefinition',
            name='interval',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
