# Generated by Django 4.2.6 on 2023-11-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0007_alter_collectordefinition_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionjob',
            name='job_type',
            field=models.CharField(default='arp', max_length=50),
            preserve_default=False,
        ),
    ]
