# Generated by Django 4.2.6 on 2023-11-09 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netbox_facts', '0010_rename_collectordefinition_collector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='run_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collector',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
