# Generated by Django 4.2.6 on 2023-11-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0011_collector_enabled_collector_run_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='last_run',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
