# Generated by Django 4.2.7 on 2023-11-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0067_ipaddress_index_host'),
        ('dcim', '0181_rename_device_role_device_role'),
        ('netbox_facts', '0012_collector_last_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='schedule_at',
        ),
        migrations.AlterField(
            model_name='collector',
            name='napalm_args',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='macaddress',
            name='known_by',
            field=models.ManyToManyField(editable=False, related_name='known_mac_addresses', through='netbox_facts.MACAddressInterfaceRelation', to='dcim.interface'),
        ),
        migrations.CreateModel(
            name='MACAddressIPAddressRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.ipaddress')),
                ('mac_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_facts.macaddress')),
            ],
            options={
                'unique_together': {('mac_address', 'ip_address')},
            },
        ),
        migrations.AddField(
            model_name='macaddress',
            name='ip_addresses',
            field=models.ManyToManyField(editable=False, related_name='mac_addresses', through='netbox_facts.MACAddressIPAddressRelation', to='ipam.ipaddress'),
        ),
    ]
