# Generated by Django 4.2.7 on 2023-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0067_ipaddress_index_host'),
        ('netbox_facts', '0013_remove_collector_schedule_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='ip_addresses',
            field=models.ManyToManyField(blank=True, editable=False, related_name='discovered_by', to='ipam.ipaddress'),
        ),
    ]
