# Generated by Django 4.2.7 on 2023-11-24 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
        ('tenancy', '0011_contactassignment_tags'),
        ('dcim', '0181_rename_device_role_device_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipam', '0067_ipaddress_index_host'),
        ('netbox_facts', '0014_collector_ip_addresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collector',
            new_name='CollectionPlan',
        ),
        migrations.RemoveField(
            model_name='macaddress',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='macaddress',
            name='known_by',
        ),
        migrations.AddField(
            model_name='macaddress',
            name='device_interface',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.interface'),
        ),
        migrations.AddField(
            model_name='macaddress',
            name='interfaces',
            field=models.ManyToManyField(editable=False, related_name='mac_addresses', through='netbox_facts.MACAddressInterfaceRelation', to='dcim.interface'),
        ),
        migrations.AddField(
            model_name='macaddress',
            name='last_seen',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='macaddress',
            name='vendor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='netbox_facts.macvendor'),
        ),
    ]
