# Generated by Django 4.2.7 on 2024-03-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0016_collectionplan_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaddress',
            name='discovery_method',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
