# Generated by Django 4.2.7 on 2024-03-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0017_macaddress_discovery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macaddress',
            name='last_seen',
        ),
    ]
