# Generated by Django 4.2.11 on 2024-04-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_facts", "0019_netbox_facts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionplan",
            name="interval",
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
    ]
