# Generated by Django 5.2.11 on 2026-02-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_facts", "0021_macaddress_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionplan",
            name="interval",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
