# Generated by Django 5.2.11 on 2026-02-26 19:30

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0021_job_queue_name"),
        ("dcim", "0226_add_mptt_tree_indexes"),
        ("extras", "0134_owner"),
        ("netbox_facts", "0022_netbox_facts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionplan",
            name="detect_only",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FactsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("comments", models.TextField(blank=True)),
                (
                    "collection_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="netbox_facts.collectionplan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.job",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Facts Report",
                "verbose_name_plural": "Facts Reports",
                "ordering": ["-created"],
                "permissions": [
                    ("apply_factsreport", "Can apply facts report entries")
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FactsReportEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("collector_type", models.CharField(max_length=50)),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=300)),
                ("detected_values", models.JSONField(default=dict)),
                ("current_values", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dcim.device",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="netbox_facts.factsreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facts Report Entry",
                "verbose_name_plural": "Facts Report Entries",
                "ordering": ["created"],
                "indexes": [
                    models.Index(
                        fields=["report", "action"],
                        name="netbox_fact_report__5597bd_idx",
                    ),
                    models.Index(
                        fields=["report", "status"],
                        name="netbox_fact_report__e16203_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="netbox_fact_object__c6393a_idx",
                    ),
                ],
            },
        ),
    ]
