# Generated by Django 5.2.11 on 2026-03-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_facts",
            "0023_factsreport_factsreportentry_collectionplan_detect_only",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionplan",
            name="connection_target",
            field=models.CharField(default="primary", max_length=20),
        ),
    ]
