# Generated by Django 5.2.11 on 2026-03-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_facts", "0025_factsreport_error_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factsreport",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="factsreport",
            name="custom_field_data",
        ),
        migrations.RemoveField(
            model_name="factsreport",
            name="tags",
        ),
    ]
