# Generated by Django 6.1 on 2026-09-17 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_facts", "0026_remove_factsreport_comments_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionplan",
            options={
                "ordering": ["priority", "name"],
                "permissions": [
                    ("run_collector", "Can run a collection plan"),
                    ("view_collector_results", "Can view collection plan run results"),
                ],
            },
        ),
    ]
