# Generated by Django 6.1 on 2026-09-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0250_cooling_infrastructure'),
        ('netbox_facts', '0029_collectionplan_allow_unscoped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsreportentry',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts_entries', to='dcim.device'),
        ),
    ]
