# Generated by Django 6.1 on 2026-10-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_facts', '0030_alter_factsreportentry_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionplan',
            name='cron_schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
